### ISSUE TITLE
Augment course instance model with new fields

### ISSUE THREAD

**Issue by martinzugnoni** [rmotr/rmotr-sis#49]
- profesor running the course
- timezone where the course is oriented to (example: EU or US)
- datetime (with timezone) when the weekly class is dictated.

Am I forgetting something?

**Comment by santiagobasulto** [comment]
`Professor == user.is_staff`? We don't have "teachers" yet, maybe it's a good time to add'em.

+1

**Comment by martinzugnoni** [comment]
Resolved by https://github.com/rmotr/rmotr-sis/pull/51
